site_name: timetracker-csv
site_url: https://dvklopfenstein.github.io/timetracker/
docs_dir: source
site_dir: ../../site
theme:
  name: mkdocs
    #custom_dir: docs_theme
    #static_templates:
    #    - index.html
  palette:
    scheme: slate
    primary: green
watch:
  - source
  - docs_theme
extra_css:
    - https://fonts.googleapis.com/css?family=Open+Sans:300,600
    - assets/colors.css
    - assets/theme.css
    - assets/highlight.css
markdown_extensions:
  - admonition
repo_url: https://github.com/dvklopfenstein/timetracker/
edit_uri: edit/main/docs/
site_author: DV Klopfenstein, PhD
site_description: Track your time on multiple projects from the CLI; Task time is saved to pandas-friendly csv files
exclude_docs: |
  /README.md
  /usage_basic_next.md
nav:
  - Home: index.md
  - Overview: overview.md
  - 'Timetracker-csv':
    - Quickstart: installation.md
    - Basic Usage: usage_basic.md
    - Advanced Usage: usage_advanced.md
    - Pandas: pandas.md
    - Invoicing: invoicing.md
  - 'Reference':
    - Global configuration File: config_global.md
  - 'Community':
    - Contributing to timetracker-csv: contributing.md

